version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qwer
      POSTGRES_DB: nest-api-core
    networks:
      - freecodecamp
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qwer
      POSTGRES_DB: nest-api-core-test
    networks:
      - freecodecamp
networks:
  freecodecamp:
